services:
  prometheus:
    image: prom/prometheus:v3.3.0
    container_name: prometheus
    restart: unless-stopped
    user: "65534:65534"
    #ports:
    #  - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:11.6.1
    container_name: grafana
    restart: unless-stopped
    user: "472:472"
    ports:
      - "127.0.0.1:24600:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: dmitry
      GF_SECURITY_ADMIN_PASSWORD: admin

    depends_on:
      - prometheus
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.1
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    #ports:
    #  - "8080:8080"
    depends_on:
      - prometheus
    networks:
      - monitoring
    restart: unless-stopped

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:v0.17.1
    container_name: postgres_exporter
    env_file:
      - .env
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${POSTGRES_SSLMODE}"
    #ports:
    #  - "9187:9187"
    networks:
      - monitoring
      - livebets
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  prometheus_data:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/prometheus/data
      o: bind
  grafana_data:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/grafana
      o: bind

networks:
  monitoring:
    external: false
  livebets:
    external: true

