###
GET https://sb2frontend-altenar2.biahosted.com/api/widget/GetLiveOverview?
    countryCode=BE&
    culture=en-GB&
    deviceType=1&
    integration=starcasino.be&
    numFormat=en-GB&
    sportId=66&
    timezoneOffset=-60
Accept: */*
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-GB;q=0.9
Origin: https://starcasinosport.be
Priority: u=1, i
Referer: https://starcasinosport.be/
Sec-Ch-Ua: "Not A(Brand";v="8", "Chromium";v="132", "Microsoft Edge";v="132"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Windows"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
Content-Type: text/plain; charset=utf-8
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.0